### ISSUE TITLE
Новая разметка сломала фильтр

### ISSUE THREAD

**Issue by LynXzp** [ivantsov/habr-comments-filter#6]
Печально, надеюсь им кто-то еще пользуется.

**Comment by ivantsov** [comment]
Здравствуйте, некоторое время назад я начал работу над новой версией (https://github.com/ivantsov/habr-comments-filter/tree/web-ext), но, к сожалению, не успел закончить её.

Не могу обещать что в скором будущем эта новая версия выйдет, но буду рад пул-реквесту.

**Comment by Owyn** [comment]
Фикс был бы кстати...

**Comment by ivantsov** [comment]
Closed by #7.
